name: Apt based Linux (AArch64)
on:
  push:
    branches:
      - master
      - fluent-package-v5
  pull_request:
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian GNU/Linux bullseye arm64
          - Debian GNU/Linux bookworm arm64
          - Ubuntu Focal arm64
          - Ubuntu Jammy arm64
          - Ubuntu Noble arm64
        include:
          - label: Debian GNU/Linux bullseye arm64
            rake-job: debian-bullseye
            test-docker-image: arm64v8/debian:bullseye
          - label: Debian GNU/Linux bookworm arm64
            rake-job: debian-bookworm
            test-docker-image: arm64v8/debian:bookworm
          - label: Ubuntu Focal arm64
            rake-job: ubuntu-focal
            rake-options: LINTIAN=no
            test-docker-image: arm64v8/ubuntu:focal
          - label: Ubuntu Jammy arm64
            rake-job: ubuntu-jammy
            rake-options: LINTIAN=no
            test-docker-image: arm64v8/ubuntu:jammy
          - label: Ubuntu Noble arm64
            rake-job: ubuntu-noble
            rake-options: LINTIAN=no
            test-docker-image: arm64v8/ubuntu:noble
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build deb with Docker
        run: |
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}-arm64 ${{ matrix.rake-options }}
      - name: Upload fluent-package deb
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}-arm64
          path: fluent-package/apt/repositories
      - name: Check Package Size
        run: |
          fluent-package/apt/pkgsize-test.sh ${{ matrix.rake-job }} arm64
      - name: Binstubs Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --env CI=true \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/apt/binstubs-test.sh
